# Form implementation generated from reading ui file 'assets/PlayerMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlayerMainWindow(object):
    def setupUi(self, PlayerMainWindow):
        PlayerMainWindow.setObjectName("PlayerMainWindow")
        PlayerMainWindow.resize(1200, 780)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlayerMainWindow.sizePolicy().hasHeightForWidth())
        PlayerMainWindow.setSizePolicy(sizePolicy)
        PlayerMainWindow.setStyleSheet("color: white;")
        self.verticalLayout = QtWidgets.QVBoxLayout(PlayerMainWindow)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Title_frame = QtWidgets.QFrame(parent=PlayerMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title_frame.sizePolicy().hasHeightForWidth())
        self.Title_frame.setSizePolicy(sizePolicy)
        self.Title_frame.setMouseTracking(True)
        self.Title_frame.setStyleSheet("background-color: rgb(42, 42, 42)")
        self.Title_frame.setObjectName("Title_frame")
        self.WindowHeader_layout = QtWidgets.QGridLayout(self.Title_frame)
        self.WindowHeader_layout.setContentsMargins(0, 0, 0, 0)
        self.WindowHeader_layout.setSpacing(0)
        self.WindowHeader_layout.setObjectName("WindowHeader_layout")
        self.Settings_button = QtWidgets.QPushButton(parent=self.Title_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Settings_button.sizePolicy().hasHeightForWidth())
        self.Settings_button.setSizePolicy(sizePolicy)
        self.Settings_button.setMaximumSize(QtCore.QSize(40, 30))
        self.Settings_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/settings-sliders.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Settings_button.setIcon(icon)
        self.Settings_button.setIconSize(QtCore.QSize(22, 22))
        self.Settings_button.setFlat(True)
        self.Settings_button.setObjectName("Settings_button")
        self.WindowHeader_layout.addWidget(self.Settings_button, 0, 8, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.WindowHeader_layout.addItem(spacerItem, 0, 6, 1, 1)
        self.Logo_label = QtWidgets.QLabel(parent=self.Title_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Logo_label.sizePolicy().hasHeightForWidth())
        self.Logo_label.setSizePolicy(sizePolicy)
        self.Logo_label.setMinimumSize(QtCore.QSize(10, 10))
        self.Logo_label.setMaximumSize(QtCore.QSize(28, 28))
        self.Logo_label.setText("")
        self.Logo_label.setPixmap(QtGui.QPixmap(":/icons/icons/spider.png"))
        self.Logo_label.setScaledContents(True)
        self.Logo_label.setIndent(50)
        self.Logo_label.setObjectName("Logo_label")
        self.WindowHeader_layout.addWidget(self.Logo_label, 0, 3, 1, 1)
        self.Minimize_button = QtWidgets.QPushButton(parent=self.Title_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Minimize_button.sizePolicy().hasHeightForWidth())
        self.Minimize_button.setSizePolicy(sizePolicy)
        self.Minimize_button.setMaximumSize(QtCore.QSize(30, 30))
        self.Minimize_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minimize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Minimize_button.setIcon(icon1)
        self.Minimize_button.setIconSize(QtCore.QSize(12, 12))
        self.Minimize_button.setObjectName("Minimize_button")
        self.WindowHeader_layout.addWidget(self.Minimize_button, 0, 10, 1, 1)
        self.Close_button = QtWidgets.QPushButton(parent=self.Title_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Close_button.sizePolicy().hasHeightForWidth())
        self.Close_button.setSizePolicy(sizePolicy)
        self.Close_button.setMaximumSize(QtCore.QSize(30, 30))
        self.Close_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Close_button.setIcon(icon2)
        self.Close_button.setIconSize(QtCore.QSize(12, 12))
        self.Close_button.setObjectName("Close_button")
        self.WindowHeader_layout.addWidget(self.Close_button, 0, 12, 1, 1)
        self.Maximize_button = QtWidgets.QPushButton(parent=self.Title_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Maximize_button.sizePolicy().hasHeightForWidth())
        self.Maximize_button.setSizePolicy(sizePolicy)
        self.Maximize_button.setMaximumSize(QtCore.QSize(30, 30))
        self.Maximize_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/expand.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Maximize_button.setIcon(icon3)
        self.Maximize_button.setIconSize(QtCore.QSize(12, 12))
        self.Maximize_button.setObjectName("Maximize_button")
        self.WindowHeader_layout.addWidget(self.Maximize_button, 0, 11, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(100, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.WindowHeader_layout.addItem(spacerItem1, 0, 2, 1, 1)
        self.CurrentlyPlaying_label = QtWidgets.QLabel(parent=self.Title_frame)
        self.CurrentlyPlaying_label.setMinimumSize(QtCore.QSize(30, 0))
        self.CurrentlyPlaying_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CurrentlyPlaying_label.setIndent(10)
        self.CurrentlyPlaying_label.setObjectName("CurrentlyPlaying_label")
        self.WindowHeader_layout.addWidget(self.CurrentlyPlaying_label, 0, 5, 1, 1)
        self.WindowTitle_label = QtWidgets.QLabel(parent=self.Title_frame)
        self.WindowTitle_label.setMinimumSize(QtCore.QSize(30, 0))
        self.WindowTitle_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.WindowTitle_label.setIndent(10)
        self.WindowTitle_label.setObjectName("WindowTitle_label")
        self.WindowHeader_layout.addWidget(self.WindowTitle_label, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.WindowHeader_layout.addItem(spacerItem2, 0, 9, 1, 1)
        self.verticalLayout.addWidget(self.Title_frame)
        self.Horizontal_splitter = QtWidgets.QSplitter(parent=PlayerMainWindow)
        self.Horizontal_splitter.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Horizontal_splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Horizontal_splitter.setHandleWidth(2)
        self.Horizontal_splitter.setObjectName("Horizontal_splitter")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.Horizontal_splitter)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setSpacing(0)
        self.searchLayout.setObjectName("searchLayout")
        self.Search_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.Search_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Search_button.setIcon(icon4)
        self.Search_button.setIconSize(QtCore.QSize(22, 22))
        self.Search_button.setFlat(True)
        self.Search_button.setObjectName("Search_button")
        self.searchLayout.addWidget(self.Search_button)
        self.Query_input = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Query_input.sizePolicy().hasHeightForWidth())
        self.Query_input.setSizePolicy(sizePolicy)
        self.Query_input.setMinimumSize(QtCore.QSize(0, 30))
        self.Query_input.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.Query_input.setStyleSheet("background-color: rgb(30, 30, 30);\n"
"color: rgb(20, 205, 255); \n"
"\n"
"/*\n"
"QLineEdit\n"
"{\n"
"    border: 1px solid black;\n"
"    background-color: black;\n"
"    border-radius: 10px;\n"
"    padding-left: 50px;\n"
"}*/")
        self.Query_input.setMaxLength(1000)
        self.Query_input.setFrame(False)
        self.Query_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Query_input.setObjectName("Query_input")
        self.searchLayout.addWidget(self.Query_input)
        self.searchLayout.setStretch(1, 30)
        self.verticalLayout_2.addLayout(self.searchLayout)
        self.PlayList_tree = QtWidgets.QTreeWidget(parent=self.horizontalLayoutWidget_2)
        self.PlayList_tree.setStyleSheet("QTreeWidget\n"
"{\n"
"    background-color: rgb(15, 15, 15);\n"
"    color: white;\n"
"    \n"
"    font: 12pt \"Helvetica Neue\";\n"
"    \n"
"}\n"
"\n"
"/*QTreeView::branch     \n"
"{\n"
"       height: 5px;\n"
"    width: 5px;\n"
"}*/\n"
"\n"
"QTreeView::branch:open \n"
"{\n"
"    image: url(\"icons/expanded.png\");\n"
"}\n"
"QTreeView::branch:closed:has-children \n"
"{\n"
"    image: url(\"icons/collapsed.png\");\n"
"}\n"
"\n"
"QTreeWidget::item\n"
"{     \n"
"    height: 50px; \n"
"}\n"
"\n"
"QTreeWidget::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    /*padding: 10px;*/\n"
"\n"
"}\n"
"\n"
"QTreeWidgetItem::indicator:enabled\n"
"{\n"
"        padding-right: 10px; /* adjust the spacing */\n"
"}\n"
"\n"
"QTreeWidget::indicator:checked {\n"
"    image: url(\"icons/star-full.png\");\n"
"}\n"
"\n"
"QTreeWidget::indicator:unchecked {\n"
"    image: url(\"icons/star-empty.png\");\n"
"}\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    \n"
"    background-color: rgb(35, 11, 63);\n"
"    border: 1px solid rgb(82, 26, 149);\n"
"    border-left-color: transparent;\n"
"    border-right-color: transparent;\n"
"}\n"
"\n"
"\n"
"/*QTreeWidgetItem[parent=1] \n"
"{ \n"
"    background-color: rgb(70, 22, 128);\n"
"}*/\n"
"\n"
"\n"
"\n"
"/*QTreeView::indicator {\n"
"    image: url(:/path/to/your/checkbox/image.png);\n"
"}*/")
        self.PlayList_tree.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.PlayList_tree.setIndentation(25)
        self.PlayList_tree.setUniformRowHeights(True)
        self.PlayList_tree.setAnimated(True)
        self.PlayList_tree.setWordWrap(True)
        self.PlayList_tree.setHeaderHidden(True)
        self.PlayList_tree.setObjectName("PlayList_tree")
        self.PlayList_tree.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.PlayList_tree)
        self.Status_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.Status_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Status_label.setStyleSheet("background-color: rgb(30, 30, 30);\n"
"color: rgb(20, 205, 255);  ")
        self.Status_label.setIndent(30)
        self.Status_label.setObjectName("Status_label")
        self.verticalLayout_2.addWidget(self.Status_label)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 100)
        self.verticalLayout_2.setStretch(2, 5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.Horizontal_splitter)
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Vertical_splitter = QtWidgets.QSplitter(parent=self.horizontalLayoutWidget_3)
        self.Vertical_splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.Vertical_splitter.setHandleWidth(2)
        self.Vertical_splitter.setObjectName("Vertical_splitter")
        self.VideoView_widget = QVideoWidget(parent=self.Vertical_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VideoView_widget.sizePolicy().hasHeightForWidth())
        self.VideoView_widget.setSizePolicy(sizePolicy)
        self.VideoView_widget.setMinimumSize(QtCore.QSize(300, 0))
        self.VideoView_widget.setMouseTracking(True)
        self.VideoView_widget.setTabletTracking(False)
        self.VideoView_widget.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.VideoView_widget.setObjectName("VideoView_widget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.Vertical_splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.botomverticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.botomverticalLayout.setContentsMargins(0, 0, 0, 0)
        self.botomverticalLayout.setSpacing(0)
        self.botomverticalLayout.setObjectName("botomverticalLayout")
        self.horizontalLayout_3.addWidget(self.Vertical_splitter)
        self.verticalLayout.addWidget(self.Horizontal_splitter)
        self.verticalLayout.setStretch(1, 10)

        self.retranslateUi(PlayerMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PlayerMainWindow)

    def retranslateUi(self, PlayerMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PlayerMainWindow.setWindowTitle(_translate("PlayerMainWindow", "SPYDER Player"))
        self.CurrentlyPlaying_label.setText(_translate("PlayerMainWindow", "[ Channel Name ]"))
        self.WindowTitle_label.setText(_translate("PlayerMainWindow", "SPYDER Player "))
        self.PlayList_tree.setSortingEnabled(False)
        self.Status_label.setText(_translate("PlayerMainWindow", "TextLabel"))
from PyQt6.QtMultimediaWidgets import QVideoWidget
