# Form implementation generated from reading ui file 'assets/About.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(780, 430)
        About.setStyleSheet("/*background-color: rgb(42, 42, 42);*/\n"
"\n"
"QLabel\n"
"{\n"
"    color: rgb(216, 216, 216);\n"
"     background-color: transparent;\n"
"}\n"
"\n"
"QPushButton \n"
"{    \n"
"    color: rgb(216, 216, 216);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"    background-color: rgb(35, 11, 63);\n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    color: rgb(73, 73, 73);\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    background-color: rgb(82, 26, 149);\n"
"}\n"
"\n"
"QTableWidget\n"
"{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTableWidget::item::selected\n"
"{\n"
"    background-color: rgb(0, 58, 201);\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: rgb(20, 6, 36);\n"
"}\n"
"\n"
"QHeaderView\n"
"{\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    color: rgb(216, 216, 216);\n"
"    background-color: rgb(0, 0, 0);\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    color: rgb(216, 216, 216);\n"
"    background-color: rgb(0, 0, 0);\n"
"    padding-left:25px;\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    color: rgb(216, 216, 216);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"     border: 1px solid grey;\n"
"     /*background: black;*/\n"
"    selection-color: rgb(216, 216, 216);\n"
"      background-color: rgb(30, 30, 30);\n"
"}\n"
"")
        self.Titlebar_widget = QtWidgets.QWidget(parent=About)
        self.Titlebar_widget.setGeometry(QtCore.QRect(0, 0, 781, 31))
        self.Titlebar_widget.setStyleSheet("background-color: rgb(27, 27, 27);")
        self.Titlebar_widget.setObjectName("Titlebar_widget")
        self.Titlebar_label = QtWidgets.QLabel(parent=self.Titlebar_widget)
        self.Titlebar_label.setGeometry(QtCore.QRect(20, 0, 251, 21))
        self.Titlebar_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Titlebar_label.setObjectName("Titlebar_label")
        self.Back_button = QtWidgets.QPushButton(parent=About)
        self.Back_button.setGeometry(QtCore.QRect(10, 380, 141, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/white-left-arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/white-left-arrow-disabled.png"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.Back_button.setIcon(icon)
        self.Back_button.setIconSize(QtCore.QSize(15, 15))
        self.Back_button.setObjectName("Back_button")
        self.License_label = QtWidgets.QLabel(parent=About)
        self.License_label.setGeometry(QtCore.QRect(50, 240, 251, 16))
        self.License_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.License_label.setObjectName("License_label")
        self.background_widget = QtWidgets.QWidget(parent=About)
        self.background_widget.setGeometry(QtCore.QRect(0, 30, 801, 421))
        self.background_widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.369, y1:0.182, x2:1, y2:1, stop:0 rgba(57, 9, 126, 255), stop:1 rgba(129, 18, 129, 255));")
        self.background_widget.setObjectName("background_widget")
        self.Title_label = QtWidgets.QLabel(parent=About)
        self.Title_label.setGeometry(QtCore.QRect(150, 40, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.Title_label.setFont(font)
        self.Title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Title_label.setObjectName("Title_label")
        self.Version_label = QtWidgets.QLabel(parent=About)
        self.Version_label.setGeometry(QtCore.QRect(140, 80, 481, 20))
        self.Version_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Version_label.setObjectName("Version_label")
        self.Name_label = QtWidgets.QLabel(parent=About)
        self.Name_label.setGeometry(QtCore.QRect(50, 200, 561, 16))
        self.Name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Name_label.setObjectName("Name_label")
        self.SourceCode_label = QtWidgets.QLabel(parent=About)
        self.SourceCode_label.setGeometry(QtCore.QRect(50, 290, 311, 16))
        self.SourceCode_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.SourceCode_label.setOpenExternalLinks(True)
        self.SourceCode_label.setObjectName("SourceCode_label")
        self.Name_label_2 = QtWidgets.QLabel(parent=About)
        self.Name_label_2.setGeometry(QtCore.QRect(50, 110, 681, 71))
        self.Name_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Name_label_2.setWordWrap(True)
        self.Name_label_2.setObjectName("Name_label_2")
        self.LicenseLink_label = QtWidgets.QLabel(parent=About)
        self.LicenseLink_label.setGeometry(QtCore.QRect(50, 260, 311, 16))
        self.LicenseLink_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.LicenseLink_label.setOpenExternalLinks(True)
        self.LicenseLink_label.setObjectName("LicenseLink_label")
        self.Copyright_label = QtWidgets.QLabel(parent=About)
        self.Copyright_label.setGeometry(QtCore.QRect(50, 330, 561, 16))
        self.Copyright_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Copyright_label.setObjectName("Copyright_label")
        self.Background_image = QtWidgets.QLabel(parent=About)
        self.Background_image.setGeometry(QtCore.QRect(360, 20, 512, 512))
        self.Background_image.setMaximumSize(QtCore.QSize(2000, 2000))
        self.Background_image.setStyleSheet("")
        self.Background_image.setText("")
        self.Background_image.setPixmap(QtGui.QPixmap(":/icons/icons/spider-black.png"))
        self.Background_image.setScaledContents(True)
        self.Background_image.setObjectName("Background_image")
        self.background_widget.raise_()
        self.Titlebar_widget.raise_()
        self.Back_button.raise_()
        self.License_label.raise_()
        self.Name_label.raise_()
        self.SourceCode_label.raise_()
        self.LicenseLink_label.raise_()
        self.Copyright_label.raise_()
        self.Background_image.raise_()
        self.Name_label_2.raise_()
        self.Title_label.raise_()
        self.Version_label.raise_()

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "Form"))
        self.Titlebar_label.setText(_translate("About", "About"))
        self.Back_button.setText(_translate("About", "  Back     "))
        self.License_label.setText(_translate("About", "License:  General Public License (GPL)"))
        self.Title_label.setText(_translate("About", "SPYDER Player"))
        self.Version_label.setText(_translate("About", "Version 1.0.0"))
        self.Name_label.setText(_translate("About", "Created by:  Fred Rodriguez"))
        self.SourceCode_label.setText(_translate("About", "<a href=\"https://github.com/ifreddyrod/SPYDER-Player\">Source Code </a>\'"))
        self.Name_label_2.setText(_translate("About", "SPYDER Player is an easy to use cross-platform media player with a focus on making streaming IPTV channels easier.  Managing playlists from various sources can be cumbersome.  SPYDER Player makes it easy to load, create, and mangage your playlists."))
        self.LicenseLink_label.setText(_translate("About", "<a href=\"https://www.gnu.org/licenses/gpl-3.0.txt\">www.gnu.org</a>\'"))
        self.Copyright_label.setText(_translate("About", "Copyright © 2024, All Rights Reserved."))
