# Form implementation generated from reading ui file 'assets/PlayerMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlayerMainWindow(object):
    def setupUi(self, PlayerMainWindow):
        PlayerMainWindow.setObjectName("PlayerMainWindow")
        PlayerMainWindow.resize(1200, 799)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/spider.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        PlayerMainWindow.setWindowIcon(icon)
        PlayerMainWindow.setStyleSheet("color: white;\n"
"background-color: black;")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(PlayerMainWindow)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Horizontal_splitter = QtWidgets.QSplitter(parent=PlayerMainWindow)
        self.Horizontal_splitter.setMinimumSize(QtCore.QSize(300, 0))
        self.Horizontal_splitter.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"\n"
"QSplitter::handle\n"
"{\n"
"    background-color: transparent;\n"
"}")
        self.Horizontal_splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Horizontal_splitter.setHandleWidth(1)
        self.Horizontal_splitter.setObjectName("Horizontal_splitter")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.Horizontal_splitter)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setSpacing(0)
        self.searchLayout.setObjectName("searchLayout")
        self.Search_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search_button.sizePolicy().hasHeightForWidth())
        self.Search_button.setSizePolicy(sizePolicy)
        self.Search_button.setMaximumSize(QtCore.QSize(32, 30))
        self.Search_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Search_button.setIcon(icon1)
        self.Search_button.setIconSize(QtCore.QSize(22, 22))
        self.Search_button.setFlat(True)
        self.Search_button.setObjectName("Search_button")
        self.searchLayout.addWidget(self.Search_button)
        self.Query_input = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Query_input.sizePolicy().hasHeightForWidth())
        self.Query_input.setSizePolicy(sizePolicy)
        self.Query_input.setMinimumSize(QtCore.QSize(0, 0))
        self.Query_input.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Query_input.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.Query_input.setStyleSheet("/*background-color: rgb(30, 30, 30);\n"
"color: rgb(20, 205, 255); */\n"
"\n"
"\n"
"QLineEdit\n"
"{\n"
"    border: 1px solid rgb(30, 30, 30);\n"
"    background-color: black;\n"
"    border-radius: 10px;\n"
"    padding-left: 25px;\n"
"    color: rgb(20, 205, 255); \n"
"}")
        self.Query_input.setMaxLength(300)
        self.Query_input.setFrame(False)
        self.Query_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Query_input.setObjectName("Query_input")
        self.searchLayout.addWidget(self.Query_input)
        self.searchLayout.setStretch(1, 30)
        self.verticalLayout_2.addLayout(self.searchLayout)
        self.PlayList_tree = QtWidgets.QTreeWidget(parent=self.horizontalLayoutWidget)
        self.PlayList_tree.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.PlayList_tree.setAutoFillBackground(False)
        self.PlayList_tree.setStyleSheet("        QTreeWidget\n"
"        {\n"
"        background-color: rgb(15, 15, 15);\n"
"        background: black;\n"
"        color: white;\n"
"        }\n"
"\n"
"        QTreeView::branch:open\n"
"        {\n"
"        image: url(\":/icons/icons/expanded.png\");\n"
"        }\n"
"        QTreeView::branch:closed:has-children\n"
"        {\n"
"        image: url(\":/icons/icons/collapsed.png\");\n"
"        }\n"
"\n"
"        QTreeWidget::item\n"
"        {\n"
"        height: 50px;\n"
"        }\n"
"\n"
"        QTreeWidget::indicator\n"
"        {\n"
"        width: 16px;\n"
"        height: 16px;\n"
"        }\n"
"\n"
"        QTreeWidgetItem::indicator:enabled\n"
"        {\n"
"        padding-right: 10px;\n"
"        }\n"
"\n"
"        QTreeWidget::indicator:checked\n"
"        {\n"
"        image: url(\":/icons/icons/star-full.png\");\n"
"        }\n"
"\n"
"        QTreeWidget::indicator:unchecked\n"
"        {\n"
"        image: url(\":/icons/icons/star-empty.png\");\n"
"        }\n"
"\n"
"        QTreeView::item:selected\n"
"        {\n"
"        background-color: rgb(30, 30, 30);\n"
"        border: 1px solid rgb(82, 26, 149);\n"
"        border-left-color: transparent;\n"
"        border-right-color: transparent;\n"
"        }\n"
"        \n"
"        QTreeView::item:hover\n"
"        {\n"
"        background-color: rgb(35, 11, 63);\n"
"        border: 1px solid rgb(82, 26, 149);\n"
"        border-left-color: transparent;\n"
"        border-right-color: transparent;\n"
"        }    \n"
"            \n"
"        QScrollBar:vertical \n"
"        {\n"
"            border: 2px solid black;\n"
"            background: black;\n"
"            width: 15px;\n"
"            margin: 22px 0 22px 0;\n"
"        }\n"
"        QScrollBar::handle:vertical \n"
"        {\n"
"            /*border: 1px solid rgb(35, 11, 63);*/\n"
"            background: rgb(82, 26, 149);\n"
"            min-height: 40px;\n"
"            border-radius: 4px; \n"
"        }\n"
"        QScrollBar::add-line:vertical \n"
"        {\n"
"            border: 2px solid rgb(35, 11, 63);\n"
"            background: rgb(82, 26, 149);\n"
"            height: 15px;\n"
"            border-radius: 4px; \n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:vertical \n"
"        {\n"
"            border: 2px solid rgb(35, 11, 63);\n"
"            background: rgb(82, 26, 149);\n"
"            height: 15px;\n"
"            border-radius: 4px; \n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"        }  \n"
"        background-color: rgb(15, 15, 15);\n"
"        border: 1px solid transparent;")
        self.PlayList_tree.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.PlayList_tree.setIndentation(25)
        self.PlayList_tree.setUniformRowHeights(True)
        self.PlayList_tree.setAnimated(True)
        self.PlayList_tree.setWordWrap(True)
        self.PlayList_tree.setHeaderHidden(True)
        self.PlayList_tree.setObjectName("PlayList_tree")
        self.PlayList_tree.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.PlayList_tree)
        self.bottomhorizontalLayout = QtWidgets.QHBoxLayout()
        self.bottomhorizontalLayout.setSpacing(0)
        self.bottomhorizontalLayout.setObjectName("bottomhorizontalLayout")
        self.Settings_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Settings_button.sizePolicy().hasHeightForWidth())
        self.Settings_button.setSizePolicy(sizePolicy)
        self.Settings_button.setMaximumSize(QtCore.QSize(32, 30))
        self.Settings_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/settings-sliders.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Settings_button.setIcon(icon2)
        self.Settings_button.setIconSize(QtCore.QSize(22, 22))
        self.Settings_button.setFlat(True)
        self.Settings_button.setObjectName("Settings_button")
        self.bottomhorizontalLayout.addWidget(self.Settings_button)
        self.Status_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.Status_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Status_label.setStyleSheet("/*background-color: rgb(30, 30, 30);\n"
"color: rgb(20, 205, 255);  */\n"
"\n"
"QLabel\n"
"{\n"
"    border: 1px solid rgb(30, 30, 30);\n"
"    background-color: black;\n"
"    border-radius: 10px;\n"
"    padding-left: 0px;\n"
"    color: rgb(20, 205, 255); \n"
"}")
        self.Status_label.setIndent(30)
        self.Status_label.setObjectName("Status_label")
        self.bottomhorizontalLayout.addWidget(self.Status_label)
        self.verticalLayout_2.addLayout(self.bottomhorizontalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 100)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.Horizontal_splitter)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Vertical_splitter = QtWidgets.QSplitter(parent=self.horizontalLayoutWidget_2)
        self.Vertical_splitter.setStyleSheet("QSplitter::handle\n"
"{\n"
"    background-color: transparent;\n"
"}")
        self.Vertical_splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.Vertical_splitter.setHandleWidth(4)
        self.Vertical_splitter.setObjectName("Vertical_splitter")
        self.VideoView_widget = QtWidgets.QWidget(parent=self.Vertical_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VideoView_widget.sizePolicy().hasHeightForWidth())
        self.VideoView_widget.setSizePolicy(sizePolicy)
        self.VideoView_widget.setObjectName("VideoView_widget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.Vertical_splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.botomverticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.botomverticalLayout.setContentsMargins(0, 0, 0, 0)
        self.botomverticalLayout.setSpacing(0)
        self.botomverticalLayout.setObjectName("botomverticalLayout")
        self.verticalLayout.addWidget(self.Vertical_splitter)
        self.verticalLayout_3.addWidget(self.Horizontal_splitter)

        self.retranslateUi(PlayerMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PlayerMainWindow)

    def retranslateUi(self, PlayerMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PlayerMainWindow.setWindowTitle(_translate("PlayerMainWindow", "SPYDER Player"))
        self.Search_button.setToolTip(_translate("PlayerMainWindow", "Search All Lists"))
        self.Query_input.setToolTip(_translate("PlayerMainWindow", "Enter Search Query (multiple phrases can be searched with + separator.  Example search: sports + 4K)"))
        self.PlayList_tree.setSortingEnabled(False)
        self.Settings_button.setToolTip(_translate("PlayerMainWindow", "Settings"))
        self.Status_label.setText(_translate("PlayerMainWindow", "TextLabel"))
