# Form implementation generated from reading ui file 'assets/PlayerSettings.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlayerSettings(object):
    def setupUi(self, PlayerSettings):
        PlayerSettings.setObjectName("PlayerSettings")
        PlayerSettings.resize(780, 430)
        PlayerSettings.setStyleSheet("/*background-color: rgb(42, 42, 42);*/\n"
"\n"
"QLabel\n"
"{\n"
"    color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton \n"
"{    \n"
"    color: rgb(216, 216, 216);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"    background-color: rgb(35, 11, 63);\n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    color: rgb(73, 73, 73);\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    background-color: rgb(82, 26, 149);\n"
"}\n"
"\n"
"QTableWidget\n"
"{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTableWidget::item::selected\n"
"{\n"
"    background-color: rgb(0, 58, 201);\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: rgb(20, 6, 36);\n"
"}\n"
"\n"
"QHeaderView\n"
"{\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    color: rgb(216, 216, 216);\n"
"    background-color: rgb(0, 0, 0);\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    color: rgb(216, 216, 216);\n"
"    background-color: rgb(0, 0, 0);\n"
"    padding-left:25px;\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    color: rgb(216, 216, 216);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"     border: 1px solid grey;\n"
"     /*background: black;*/\n"
"    selection-color: rgb(216, 216, 216);\n"
"      background-color: rgb(30, 30, 30);\n"
"}\n"
"")
        self.Titlebar_widget = QtWidgets.QWidget(parent=PlayerSettings)
        self.Titlebar_widget.setGeometry(QtCore.QRect(0, 0, 781, 31))
        self.Titlebar_widget.setStyleSheet("background-color: rgb(27, 27, 27);")
        self.Titlebar_widget.setObjectName("Titlebar_widget")
        self.Titlebar_label = QtWidgets.QLabel(parent=self.Titlebar_widget)
        self.Titlebar_label.setGeometry(QtCore.QRect(20, 0, 251, 21))
        self.Titlebar_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Titlebar_label.setObjectName("Titlebar_label")
        self.Back_button = QtWidgets.QPushButton(parent=PlayerSettings)
        self.Back_button.setGeometry(QtCore.QRect(10, 380, 141, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/white-left-arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/white-left-arrow-disabled.png"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.Back_button.setIcon(icon)
        self.Back_button.setIconSize(QtCore.QSize(15, 15))
        self.Back_button.setObjectName("Back_button")
        self.PlayerType_combobox = QtWidgets.QComboBox(parent=PlayerSettings)
        self.PlayerType_combobox.setGeometry(QtCore.QRect(180, 60, 191, 30))
        self.PlayerType_combobox.setStyleSheet("color: rgb(20, 205, 255); \n"
"")
        self.PlayerType_combobox.setObjectName("PlayerType_combobox")
        self.PlayerType_combobox.addItem("")
        self.PlayerType_combobox.addItem("")
        self.PlayerType_label = QtWidgets.QLabel(parent=PlayerSettings)
        self.PlayerType_label.setGeometry(QtCore.QRect(40, 70, 131, 16))
        self.PlayerType_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.PlayerType_label.setObjectName("PlayerType_label")
        self.background_widget = QtWidgets.QWidget(parent=PlayerSettings)
        self.background_widget.setGeometry(QtCore.QRect(0, 30, 801, 421))
        self.background_widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.369, y1:0.182, x2:1, y2:1, stop:0 rgba(57, 9, 126, 255), stop:1 rgba(129, 18, 129, 255));")
        self.background_widget.setObjectName("background_widget")
        self.PlaylistPath_textedit = QtWidgets.QTextEdit(parent=PlayerSettings)
        self.PlaylistPath_textedit.setGeometry(QtCore.QRect(180, 170, 481, 51))
        self.PlaylistPath_textedit.setStyleSheet("border-radius: 10px;\n"
"color: rgb(20, 205, 255); \n"
"padding-left: 40px;")
        self.PlaylistPath_textedit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.PlaylistPath_textedit.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.PlaylistPath_textedit.setObjectName("PlaylistPath_textedit")
        self.OpenPath_button = QtWidgets.QPushButton(parent=PlayerSettings)
        self.OpenPath_button.setGeometry(QtCore.QRect(179, 170, 31, 51))
        self.OpenPath_button.setStyleSheet("border-radius: 10px;\n"
"/*background-color: rgba(0, 0, 0, 0);*/\n"
"")
        self.OpenPath_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/white-folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/white-folder-disabled.png"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.OpenPath_button.setIcon(icon1)
        self.OpenPath_button.setIconSize(QtCore.QSize(20, 20))
        self.OpenPath_button.setObjectName("OpenPath_button")
        self.Path_label = QtWidgets.QLabel(parent=PlayerSettings)
        self.Path_label.setGeometry(QtCore.QRect(40, 180, 131, 16))
        self.Path_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Path_label.setObjectName("Path_label")
        self.Save_button = QtWidgets.QPushButton(parent=PlayerSettings)
        self.Save_button.setGeometry(QtCore.QRect(630, 380, 141, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/white-diskette.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/white-diskette-disabled.png"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.Save_button.setIcon(icon2)
        self.Save_button.setIconSize(QtCore.QSize(20, 20))
        self.Save_button.setObjectName("Save_button")
        self.background_widget.raise_()
        self.Titlebar_widget.raise_()
        self.Back_button.raise_()
        self.PlayerType_combobox.raise_()
        self.PlayerType_label.raise_()
        self.PlaylistPath_textedit.raise_()
        self.OpenPath_button.raise_()
        self.Path_label.raise_()
        self.Save_button.raise_()

        self.retranslateUi(PlayerSettings)
        QtCore.QMetaObject.connectSlotsByName(PlayerSettings)

    def retranslateUi(self, PlayerSettings):
        _translate = QtCore.QCoreApplication.translate
        PlayerSettings.setWindowTitle(_translate("PlayerSettings", "Form"))
        self.Titlebar_label.setText(_translate("PlayerSettings", "Player Settings"))
        self.Back_button.setText(_translate("PlayerSettings", "  Back     "))
        self.PlayerType_combobox.setItemText(0, _translate("PlayerSettings", "VLC"))
        self.PlayerType_combobox.setItemText(1, _translate("PlayerSettings", "QTMEDIA"))
        self.PlayerType_label.setText(_translate("PlayerSettings", "Player Type:"))
        self.PlaylistPath_textedit.setPlaceholderText(_translate("PlayerSettings", "Select or paste Default Path for Playlists"))
        self.Path_label.setText(_translate("PlayerSettings", "Default Playlist Path:"))
        self.Save_button.setText(_translate("PlayerSettings", "  Save"))
