# Form implementation generated from reading ui file 'assets/SplashScreen.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        SplashScreen.resize(479, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SplashScreen.sizePolicy().hasHeightForWidth())
        SplashScreen.setSizePolicy(sizePolicy)
        SplashScreen.setStyleSheet("color: rgb(216, 216, 216);")
        self.Background_image = QtWidgets.QLabel(parent=SplashScreen)
        self.Background_image.setGeometry(QtCore.QRect(10, -40, 461, 401))
        self.Background_image.setMaximumSize(QtCore.QSize(2000, 2000))
        self.Background_image.setStyleSheet("")
        self.Background_image.setText("")
        self.Background_image.setPixmap(QtGui.QPixmap(":/icons/icons/spider-black.png"))
        self.Background_image.setScaledContents(True)
        self.Background_image.setObjectName("Background_image")
        self.Title_label = QtWidgets.QLabel(parent=SplashScreen)
        self.Title_label.setGeometry(QtCore.QRect(0, 0, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.Title_label.setFont(font)
        self.Title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Title_label.setObjectName("Title_label")
        self.Version_label = QtWidgets.QLabel(parent=SplashScreen)
        self.Version_label.setGeometry(QtCore.QRect(0, 50, 481, 20))
        self.Version_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Version_label.setObjectName("Version_label")
        self.Status_label = QtWidgets.QLabel(parent=SplashScreen)
        self.Status_label.setGeometry(QtCore.QRect(0, 260, 481, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Status_label.sizePolicy().hasHeightForWidth())
        self.Status_label.setSizePolicy(sizePolicy)
        self.Status_label.setStyleSheet("QLabel\n"
"{\n"
"    background:  rgba(255, 255, 255, 64);\n"
"    /*border-radius: 10px;*/\n"
"    color: white;\n"
"}")
        self.Status_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Status_label.setObjectName("Status_label")
        self.background = QtWidgets.QWidget(parent=SplashScreen)
        self.background.setGeometry(QtCore.QRect(0, -1, 531, 381))
        self.background.setStyleSheet("/*background-color: qlineargradient(spread:pad, x1:0.074, y1:0.968409, x2:0.881759, y2:0.221591, stop:0 rgba(209, 30, 255, 255), stop:1 rgba(37, 189, 255, 255));*/\n"
"\n"
"/*background-color: rgb(20, 5, 37);  */\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0.369, y1:0.182, x2:1, y2:1, stop:0 rgba(57, 9, 126, 255), stop:1 rgba(129, 18, 129, 255));")
        self.background.setObjectName("background")
        self.background.raise_()
        self.Background_image.raise_()
        self.Title_label.raise_()
        self.Version_label.raise_()
        self.Status_label.raise_()

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "Spyder Player - SpashScreen"))
        self.Title_label.setText(_translate("SplashScreen", "SPYDER Player"))
        self.Version_label.setText(_translate("SplashScreen", "Version 1.0.0"))
        self.Status_label.setText(_translate("SplashScreen", "TextLabel"))
