# Form implementation generated from reading ui file 'assets/Settings.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsMain(object):
    def setupUi(self, SettingsMain):
        SettingsMain.setObjectName("SettingsMain")
        SettingsMain.resize(780, 430)
        SettingsMain.setStyleSheet("/*background-color: rgb(42, 42, 42);*/\n"
"\n"
"QLabel\n"
"{\n"
"    color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton \n"
"{    \n"
"    color: rgb(216, 216, 216);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"    background-color: rgb(35, 11, 63);\n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    color: rgb(73, 73, 73);\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    background-color: rgb(82, 26, 149);\n"
"}\n"
"\n"
"QTableWidget\n"
"{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTableWidget::item::selected\n"
"{\n"
"    background-color: rgb(0, 58, 201);\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: rgb(20, 6, 36);\n"
"}\n"
"\n"
"QHeaderView\n"
"{\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.Titlebar_widget = QtWidgets.QWidget(parent=SettingsMain)
        self.Titlebar_widget.setGeometry(QtCore.QRect(0, 0, 781, 31))
        self.Titlebar_widget.setStyleSheet("/*background-color: rgb(20, 6, 36);*/\n"
"background-color: rgb(27, 27, 27);")
        self.Titlebar_widget.setObjectName("Titlebar_widget")
        self.Titlebar_label = QtWidgets.QLabel(parent=self.Titlebar_widget)
        self.Titlebar_label.setGeometry(QtCore.QRect(20, 0, 251, 21))
        self.Titlebar_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Titlebar_label.setObjectName("Titlebar_label")
        self.PlayList_button = QtWidgets.QPushButton(parent=SettingsMain)
        self.PlayList_button.setGeometry(QtCore.QRect(170, 50, 261, 51))
        self.PlayList_button.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/playlist.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PlayList_button.setIcon(icon)
        self.PlayList_button.setIconSize(QtCore.QSize(24, 24))
        self.PlayList_button.setObjectName("PlayList_button")
        self.Close_button = QtWidgets.QPushButton(parent=SettingsMain)
        self.Close_button.setGeometry(QtCore.QRect(10, 380, 141, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/white-left-arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Close_button.setIcon(icon1)
        self.Close_button.setIconSize(QtCore.QSize(15, 15))
        self.Close_button.setObjectName("Close_button")
        self.Library_button = QtWidgets.QPushButton(parent=SettingsMain)
        self.Library_button.setGeometry(QtCore.QRect(170, 110, 261, 51))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/library.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Library_button.setIcon(icon2)
        self.Library_button.setIconSize(QtCore.QSize(24, 24))
        self.Library_button.setObjectName("Library_button")
        self.HotKeys_button = QtWidgets.QPushButton(parent=SettingsMain)
        self.HotKeys_button.setGeometry(QtCore.QRect(170, 310, 261, 51))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/keyboard.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.HotKeys_button.setIcon(icon3)
        self.HotKeys_button.setIconSize(QtCore.QSize(24, 24))
        self.HotKeys_button.setObjectName("HotKeys_button")
        self.background_widget = QtWidgets.QWidget(parent=SettingsMain)
        self.background_widget.setGeometry(QtCore.QRect(0, 10, 801, 421))
        self.background_widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.369, y1:0.182, x2:1, y2:1, stop:0 rgba(57, 9, 126, 255), stop:1 rgba(129, 18, 129, 255));")
        self.background_widget.setObjectName("background_widget")
        self.OpenMediaFile_button = QtWidgets.QPushButton(parent=SettingsMain)
        self.OpenMediaFile_button.setGeometry(QtCore.QRect(480, 110, 261, 51))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/videofile.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.OpenMediaFile_button.setIcon(icon4)
        self.OpenMediaFile_button.setIconSize(QtCore.QSize(24, 24))
        self.OpenMediaFile_button.setObjectName("OpenMediaFile_button")
        self.OpenPlayList_button = QtWidgets.QPushButton(parent=SettingsMain)
        self.OpenPlayList_button.setGeometry(QtCore.QRect(480, 50, 261, 51))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/playlists.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.OpenPlayList_button.setIcon(icon5)
        self.OpenPlayList_button.setIconSize(QtCore.QSize(24, 24))
        self.OpenPlayList_button.setObjectName("OpenPlayList_button")
        self.Favorites_button = QtWidgets.QPushButton(parent=SettingsMain)
        self.Favorites_button.setGeometry(QtCore.QRect(170, 170, 261, 51))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/star-white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Favorites_button.setIcon(icon6)
        self.Favorites_button.setIconSize(QtCore.QSize(24, 24))
        self.Favorites_button.setObjectName("Favorites_button")
        self.PlayerSettings_button = QtWidgets.QPushButton(parent=SettingsMain)
        self.PlayerSettings_button.setGeometry(QtCore.QRect(170, 250, 261, 51))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PlayerSettings_button.setIcon(icon7)
        self.PlayerSettings_button.setIconSize(QtCore.QSize(24, 24))
        self.PlayerSettings_button.setObjectName("PlayerSettings_button")
        self.background_widget.raise_()
        self.Titlebar_widget.raise_()
        self.PlayList_button.raise_()
        self.Close_button.raise_()
        self.Library_button.raise_()
        self.HotKeys_button.raise_()
        self.OpenMediaFile_button.raise_()
        self.OpenPlayList_button.raise_()
        self.Favorites_button.raise_()
        self.PlayerSettings_button.raise_()

        self.retranslateUi(SettingsMain)
        QtCore.QMetaObject.connectSlotsByName(SettingsMain)

    def retranslateUi(self, SettingsMain):
        _translate = QtCore.QCoreApplication.translate
        SettingsMain.setWindowTitle(_translate("SettingsMain", "Form"))
        self.Titlebar_label.setText(_translate("SettingsMain", "Settings"))
        self.PlayList_button.setText(_translate("SettingsMain", "   PlayList Editor"))
        self.Close_button.setText(_translate("SettingsMain", "  Close     "))
        self.Library_button.setText(_translate("SettingsMain", "   Library Editor"))
        self.HotKeys_button.setText(_translate("SettingsMain", "   Hot Keys"))
        self.OpenMediaFile_button.setText(_translate("SettingsMain", "   Open Media File"))
        self.OpenPlayList_button.setText(_translate("SettingsMain", "   Open PlayList"))
        self.Favorites_button.setText(_translate("SettingsMain", "   Favorites Editor"))
        self.PlayerSettings_button.setText(_translate("SettingsMain", "   Player Settings"))
